### PR TITLE
#2294 user account register xml

### LINKED ISSUE #2294: SAXParseException processing WAAccount XML
Using master branch processing an UFDR file generated by PA 10.3:

```
bytes)		org.apache.tika.exception.TikaException: Failed to detect the character encoding of a document
[Fatal Error] :1:1: Content is not allowed in prolog.
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
	at iped.parsers.whatsapp.WAAccount.getFromAndroidXml(WAAccount.java:37)
	at iped.parsers.whatsapp.WhatsAppParser.parseWhatsAppAccount(WhatsAppParser.java:795)
	at iped.parsers.whatsapp.WhatsAppParser.parse(WhatsAppParser.java:252)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at iped.parsers.standard.StandardParser.parse(StandardParser.java:245)
	at iped.engine.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by aberenguel**
Fixes #2294 where `com.whatsapp.w4b_preferences_light.xml` is "corrupted" but `registration.RegisterPhone.xml` has valuable information.

### CODE REVIEW

**Comment by wladimirleite** [comment]
Hi @aberenguel!
Let me know when you finish, so I can review this.

**Comment by aberenguel** [comment]
I think you can review now.

The WA account can have properties spread in some XML files and possibly in contact database. The indexed WA account can be built after such info be indexed, so now it is child of wa.db.  I will send you some ufdr files as example.

**Comment by wladimirleite** [comment]
Great! Please put some samples in our local server. I am trying to find/produce more samples, but usinh yours will help a lot for now.

File: iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java [hunk 1]
```diff
@@ -793,6 +806,41 @@ private void parseWhatsAppAccount(InputStream is, ParseContext context, ContentH
...
+        } catch (Exception e) {
+           logger.warn("Error filling WhatsApp account with contact data: " + account.getFullId(), e);
+        }
+    }
+
+    private void fillAccountAvatar(WAAccount account, IItemSearcher searcher, String dbPath) {
+        if (account == null || account.getAvatar() != null || account.getAvatarPath() != null) {
+            return;
+        }
+        String filePath = Paths.get(dbPath).getParent().resolveSibling("files").resolve("me.jpg").toString().replace("\\", "/");
```
Comment (wladimirleite) [inline iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java:829]: This line is causing a critical (abort) error, if dbPath is a container (e.g. ZIP), because the path becomes something like "a.zip>>data/Root/data/com.whatsapp/databases/wa.db", which is not accepted by the `Path.get()` as it is not a valid path (contains ">").
Although wa.db is not usually inside a container, it is a possible situation.
I will modify the code, to avoid this exception.

Comment (lfcnassif) [reply iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java]: It can be inside a zip/tar FFS extraction when processed directly. It will be more common in the future when #2095 is merged.

**Review by wladimirleite — APPROVED** [review]
@lfcnassif, I finished testing this PR. 
I made a small fix and asked @aberenguel to check it, but other than that, it seems ready to be merged.

**Comment by lfcnassif** [comment]
Thanks @aberenguel for this PR and @wladimirleite for reviewing and testing! Merging. @aberenguel please let me know if @wladimirleite's fix is not ok.

File: iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WAAccount.java [hunk 2]
```diff
@@ -27,48 +31,69 @@ public WAAccount(String id) {
...
                 value = (String) expr.evaluate(doc, XPathConstants.STRING);
-                if (value == null || value.isBlank())
-                    return null;
+                if (StringUtils.isNotBlank(value)) {
+                    String countryCode = value;
+                    id = countryCode + phoneNumber + waSuffix;
+                }
+            } else {
+                expr = xpath.compile("/map/string[@name=\"registration_jid\"]");
+                value = (String) expr.evaluate(doc, XPathConstants.STRING);
```
[the remark this answers is not in the document]
Comment (aberenguel) [reply iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WAAccount.java:60]: Just checked! The code definitely had a bug. The fix seems to solve it. Thanks, @wladimirleite .

File: iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java (hunk 1 above)
Comment (aberenguel) [reply iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java]: Great! I hadn't thought about that!

**Comment by aberenguel** [comment]
> Thanks @aberenguel for this PR and @wladimirleite for reviewing and testing! Merging. @aberenguel please let me know if you think @wladimirleite's fixes are not ok.

The code had a bug. @wladimirleite fix solved it. It seems to work like a charm.
